apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oradata-storage-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: "5Gi"
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe-pv
  labels:
    run: oracle-xe-pv    
    app: oracle-xe
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: oracle-xe
  template:
    metadata:
      name: oracle-xe-pv
      labels:
        run: oracle-xe-pv    
        app: oracle-xe
        version: 21.3.0
    spec:
      volumes:
        - name: oradata-storage
          persistentVolumeClaim:
            claimName: oradata-storage-pvc
      containers:
        - name: oracle-xe-pv
          image: container-registry.oracle.com/database/express:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "1.0"
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: oradata-storage
              mountPath: "/opt/oracle/oradata"
          env:
            - name: ORACLE_PWD
              value: "GoodMorning2023"
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-xe-pv
  labels:
    app: oracle-xe
    version: 21.3.0
spec:
  selector: 
    app: oracle-xe
    version: 21.3.0
  type: NodePort
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500